# SPDX-FileCopyrightText: Copyright (C) 2025 Roman Lupashko (CuberHuber)
# SPDX-License-Identifier: MIT
---
threshold: 10
model: true
errors:
  - lupashcko.rom@icloud.com
#alerts:
#  suppress:
#    - on-found-puzzle
#    - on-lost-puzzle
#    - on-scope
#  github:
#    - CuberHuber
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - bug
